# This workflow will build an android project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Check Spotless
        run: sudo ./gradlew spotlessCheck

      - name: Check Lint
        run: sudo ./gradlew lintDebug

      - name: Run tests
        run: sudo ./gradlew test

      - name: Build with Gradle
        run: sudo ./gradlew build
